[package]
name = "Todo"
version = "1.70.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "todo"
path = "src/todo.rs"

[dependencies]
